# Generated by Django 5.2.17 on 2026-09-24

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(
                default='#6c757d',
                help_text='HEX rang, masalan #ff0000',
                max_length=7,
                validators=[django.core.validators.RegexValidator(
                    '^#[0-9A-Fa-f]{6}$',
                    'Rang #RRGGBB formatida bo\'lishi kerak.',
                )],
            ),
        ),
    ]