# Generated by Django 5.2.17 on 2026-09-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tag_color'),
        ('tasks', '0003_alter_comment_text_alter_comment_user_and_more'),
    ]

    operations = [
    ]
